# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/BrycensRanch/Rokon
%global goipath         github.com/BrycensRanch/Rokon
%global commit          8b62bba42770b0392b9e6832ae5cbc939f133c90

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE.md assets/LICENSE.md
%global godocs          .markdownlint.json PRIVACY.md README.md\\\
                        debian/README.md debian/changelog flathub/README.md\\\
                        flathub/modules.txt windows/portable.txt

Name:           golang-github-brycensranch-rokon
Version:        0
Release:        %autorelease -p
Summary:        None

License:        CC-BY-SA-4.0 AND AGPL-3.0-only
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
%gobuild -o %{gobuilddir}/bin/Rokon %{goipath}
for cmd in scripts/copr scripts/rtf2plaintext; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE.md assets/LICENSE.md
%doc .markdownlint.json PRIVACY.md README.md debian/README.md debian/changelog
%doc flathub/README.md flathub/modules.txt windows/portable.txt
%{_bindir}/Rokon
%endif

%gopkgfiles

%changelog
%autochangelog
