# Generated by go2rpm 1.14.0
%bcond check 1

# https://github.com/brycensranch/rokon
%global goipath         github.com/brycensranch/rokon
%global commit          055b881b75129b45495c0cc2743fd237ed6a62cb

%gometa -L -f

%global common_description %{expand:
# FIXME}

Name:           golang-github-brycensranch-rokon
Version:        0
Release:        %autorelease -p
Summary:        None

# Generated by go-vendor-tools
License:        AGPL-3.0-only AND BSD-3-Clause AND CC-BY-SA-4.0 AND GPL-3.0-or-later AND ISC AND MIT AND MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description %{common_description}

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%gobuild -o %{gobuilddir}/bin/rokon %{goipath}
for cmd in scripts/copr scripts/md2rtf scripts/rtf2plaintext; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gocheck
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc .markdownlint.json PRIVACY.md README.md debian/README.md debian/changelog
%doc flathub/README.md flathub/modules.txt windows/portable.txt
%{_bindir}/rokon


%changelog
%autochangelog
