# Generated by go2rpm 1.14.0
%bcond check 0
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/brycensranch/go-aptabase
%global goipath         github.com/brycensranch/go-aptabase
%global commit          e20856549654b6fb0d66eeb4b6c1ae3a4ea36cd1

%gometa -L -f

%global common_description %{expand:
Golang SDK for Aptabase: Open Source, Privacy-First and Simple Analytics for
Mobile, Desktop and Web Apps.}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           golang-github-brycensranch-aptabase
Version:        0
Release:        %autorelease -p
Summary:        Golang SDK for Aptabase: Open Source, Privacy-First and Simple Analytics for Mobile, Desktop and Web Apps

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
