PORTNAME=	     rokon
PORTVERSION=     1.0.0
DISTNAME=	${PORTNAME}${PORTVERSION}
CATEGORIES=	     utility
MASTER_SITES=    https://github.com/BrycensRanch/Rokon/archive/master.tar.gz
MAINTAINER=      brycengranville@outlook.com
COMMENT=         Control your Roku device with your desktop!
WWW=             https://github.com/BrycensRanch/Rokon
LICENSE=         AGPL-3.0-or-later
USES=		tar:tgz


.include <bsd.port.mk>
